# Generated by Django 3.2 on 2021-06-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FEI', '0004_compartir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartir',
            name='password',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='FEI.password'),
        ),
    ]
