# Generated by Django 3.2 on 2021-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEI', '0006_alter_compartir_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartir',
            name='contrasenas',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
