# Generated by Django 3.1 on 2021-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEI', '0009_auto_20210625_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='doblea',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('contain', models.IntegerField(default=0)),
                ('ultima', models.DateTimeField()),
            ],
        ),
    ]
